In [1]:
import pandas as pd
from util import DataFile

In [2]:
import util

In [3]:
path = "data/csv/team/" #팀별 데이터가 있는 디렉토리
data = DataFile(path).load_csv()

100%|████████████████████████████████████████████████████████████████████████████████| 493/493 [00:05<00:00, 93.80it/s]

In [4]:
local_leagues = ['Bundesliga 1', 'Serie A','La Liga', 'Ligue 1','Premier League']
local_data = data[data['league_name'].isin(local_leagues)]

In [6]:
local_data

,Unnamed: 0,id,name,firstname,lastname,age,birth_date,birth_place,birth_country,nationality,...,fouls_drawn,fouls_committed,cards_yellow,cards_yellowred,cards_red,penalty_won,penalty_commited,penalty_scored,penalty_missed,penalty_saved
0,0,426,M. Uth,Mark,Uth,31.0,1991-08-24,Köln,Germany,Germany,...,25.0,50.0,5.0,0.0,0.0,1.0,NaN,0.0,0.0,NaN
4,4,702,O. Baumann,Oliver,Baumann,32.0,1990-06-02,Breisach,Germany,Germany,...,5.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.0
8,8,703,A. Stolz,Alexander,Stolz,38.0,1983-10-13,Pforzheim,Germany,Germany,...,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
11,11,705,E. Bičakčić,Ermin,Bičakčić,32.0,1990-01-24,Zvornik,Bosnia and Herzegovina,Bosnia and Herzegovina,...,4.0,10.0,4.0,0.0,0.0,NaN,1.0,0.0,0.0,NaN
15,15,709,P. Kadeřábek,Pavel,Kadeřábek,30.0,1992-04-25,Praha,Czech Republic,Czech Republic,...,21.0,35.0,5.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,43,41606,Toti,Tote António,Gomes,23.0,1999-01-16,NaN,Portugal,Portugal,...,1.0,1.0,1.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN
45,45,152964,Christian Fernandes Marques,Christian,Fernandes Marques,19.0,2003-01-15,Uster,Switzerland,Portugal,...,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN
48,48,280687,Hugo Bueno,Hugo,Bueno López,20.0,2002-09-18,Vigo,Spain,Spain,...,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN
50,50,284237,D. Lembikisa,Dexter,Lembikisa,19.0,2003-11-04,NaN,England,England,...,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
52,52,288115,J. Storer,James,Storer,NaN,NaN,NaN,England,England,...,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0

In [10]:
    local_data = local_data[(local_data['games_appearences']>=5)&(local_data['games_minutes']!=0)]
    local_data=local_data.fillna(0)
    #target_data = pd.DataFrame()
    #for proportion in proportions:
    #    target_data[proportion] = data[proportion]/data['games_minutes']
    #target_data['games_rating'] = data['games_rating']

In [11]:
local_data

,Unnamed: 0,id,name,firstname,lastname,age,birth_date,birth_place,birth_country,nationality,...,fouls_drawn,fouls_committed,cards_yellow,cards_yellowred,cards_red,penalty_won,penalty_commited,penalty_scored,penalty_missed,penalty_saved
0,0,426,M. Uth,Mark,Uth,31.0,1991-08-24,Köln,Germany,Germany,...,25.0,50.0,5.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,4,702,O. Baumann,Oliver,Baumann,32.0,1990-06-02,Breisach,Germany,Germany,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11,11,705,E. Bičakčić,Ermin,Bičakčić,32.0,1990-01-24,Zvornik,Bosnia and Herzegovina,Bosnia and Herzegovina,...,4.0,10.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
15,15,709,P. Kadeřábek,Pavel,Kadeřábek,30.0,1992-04-25,Praha,Czech Republic,Czech Republic,...,21.0,35.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,19,721,N. Schulz,Nico,Schulz,29.0,1993-04-01,Berlin,Germany,Germany,...,21.0,22.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,27,18740,Jonny Castro,Jonathan,Castro Otto,28.0,1994-03-03,Vigo,Spain,Spain,...,15.0,9.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,30,18741,C. Coady,Conor,Coady,29.0,1993-02-25,St Helens,England,England,...,1.0,17.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,33,18744,M. Kilman,Maximilian,Kilman,25.0,1997-05-23,London,England,England,...,10.0,16.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,36,18753,Adama Traoré,Adama,Traoré Diarra,26.0,1996-01-25,L'Hospitalet de Llobregat,Spain,Spain,...,26.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,40,21138,R. Aït Nouri,Rayan,Aït Nouri,21.0,2001-06-06,Montreuil,France,France,...,14.0,13.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
proportions = ['shots_total', 'shots_on', 'goals_total', 'goals_conceded', 'goals_assists', 'goals_saves', 'passes_total', 'passes_accuracy', 'passes_key',  'tackles_total', 'tackles_blocks', 'tackles_interceptions'
, 'duels_total', 'duels_won', 'dribbles_attempts', 'dribbles_success', 'dribbles_past', 'fouls_drawn', 'fouls_committed', 'cards_yellow', 'cards_red', 'penalty_won', 'penalty_commited', 'penalty_scored', 'penalty_missed', 'penalty_saved']

In [29]:
target_data = pd.DataFrame()
for proportion in proportions:
    target_data[proportion] = local_data[proportion]/local_data['games_minutes']
target_data['games_rating'] = local_data['games_rating']
target_data['games_position'] = local_data['games_position']

In [19]:
local_data.columns

Index(['Unnamed: 0', 'id', 'name', 'firstname', 'lastname', 'age',
       'birth_date', 'birth_place', 'birth_country', 'nationality', 'height',
       'weight', 'injured', 'photo', 'team_id', 'team_name', 'team_logo',
       'league_id', 'league_name', 'league_country', 'league_logo',
       'league_flag', 'league_season', 'games_appearences', 'games_lineups',
       'games_minutes', 'games_number', 'games_position', 'games_rating',
       'games_captain', 'substitutes_in', 'substitutes_out',
       'substitutes_bench', 'shots_total', 'shots_on', 'goals_total',
       'goals_conceded', 'goals_assists', 'goals_saves', 'passes_total',
       'passes_key', 'passes_accuracy', 'tackles_total', 'tackles_blocks',
       'tackles_interceptions', 'duels_total', 'duels_won',
       'dribbles_attempts', 'dribbles_success', 'dribbles_past', 'fouls_drawn',
       'fouls_committed', 'cards_yellow', 'cards_yellowred', 'cards_red',
       'penalty_won', 'penalty_commited', 'penalty_scored', 'penalty_missed',
       'penalty_saved'],
      dtype='object')

In [30]:
target_data

,shots_total,shots_on,goals_total,goals_conceded,goals_assists,goals_saves,passes_total,passes_accuracy,passes_key,tackles_total,...,fouls_committed,cards_yellow,cards_red,penalty_won,penalty_commited,penalty_scored,penalty_missed,penalty_saved,games_rating,games_position
0,0.024805,0.010106,0.006431,0.000000,0.003675,0.00000,0.184198,0.033073,0.013321,0.002756,...,0.022967,0.002297,0.0,0.000459,0.000000,0.0,0.0,0.000000,7.122580,Attacker
4,0.000000,0.000000,0.000000,0.015686,0.000000,0.03366,0.280719,0.021895,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000327,6.797058,Goalkeeper
11,0.003643,0.003643,0.000000,0.000000,0.000000,0.00000,0.455373,0.145719,0.001821,0.005464,...,0.018215,0.007286,0.0,0.000000,0.001821,0.0,0.0,0.000000,6.644444,Defender
15,0.010469,0.003186,0.000910,0.000000,0.001365,0.00000,0.270824,0.033682,0.010469,0.003186,...,0.015931,0.002276,0.0,0.000000,0.000000,0.0,0.0,0.000000,6.882142,Defender
19,0.009588,0.003948,0.000564,0.000000,0.001128,0.00000,0.341230,0.041737,0.015228,0.006768,...,0.012408,0.001692,0.0,0.000564,0.000000,0.0,0.0,0.000000,6.870370,Defender
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,0.011194,0.007463,0.003731,0.000000,0.000000,0.00000,0.498134,0.055970,0.013060,0.024254,...,0.016791,0.001866,0.0,0.000000,0.000000,0.0,0.0,0.000000,6.928571,Defender
30,0.002441,0.001046,0.001046,0.000000,0.000000,0.00000,0.459902,0.013250,0.000349,0.009414,...,0.005927,0.001395,0.0,0.000000,0.000000,0.0,0.0,0.000000,7.096774,Defender
33,0.003347,0.001488,0.000372,0.000000,0.000000,0.00000,0.538118,0.015619,0.001116,0.017851,...,0.005950,0.001116,0.0,0.000000,0.000000,0.0,0.0,0.000000,7.048275,Defender
36,0.011289,0.004704,0.000941,0.000000,0.000000,0.00000,0.280339,0.011289,0.017874,0.007526,...,0.009407,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,7.036842,Attacker
40,0.004354,0.001451,0.000000,0.000000,0.001451,0.00000,0.419448,0.017417,0.010885,0.036284,...,0.009434,0.002903,0.0,0.000000,0.000000,0.0,0.0,0.000000,6.938888,Defender

In [36]:
GK_data=target_data[target_data['games_position']=='Goalkeeper']
DF_data=target_data[target_data['games_position']=='Defender']
AT_data=target_data[target_data['games_position']=='Attacker']
MF_data=target_data[target_data['games_position']=='Midfielder']

In [37]:
GK_data.corr().loc[:,'games_rating']

shots_total              0.006083
shots_on                 0.086611
goals_total              0.049804
goals_conceded          -0.566506
goals_assists            0.012747
goals_saves              0.339186
passes_total             0.037631
passes_accuracy         -0.041446
passes_key              -0.051732
tackles_total            0.070607
tackles_blocks                NaN
tackles_interceptions    0.051745
duels_total             -0.066113
duels_won               -0.001968
dribbles_attempts       -0.107187
dribbles_success        -0.124543
dribbles_past                 NaN
fouls_drawn              0.050779
fouls_committed         -0.168819
cards_yellow             0.018906
cards_red               -0.160672
penalty_won                   NaN
penalty_commited              NaN
penalty_scored                NaN
penalty_missed           0.043275
penalty_saved           -0.086801
games_rating             1.000000
Name: games_rating, dtype: float64

In [38]:
DF_data.corr().loc[:,'games_rating']

shots_total              0.184046
shots_on                 0.157052
goals_total              0.120676
goals_conceded                NaN
goals_assists            0.126616
goals_saves                   NaN
passes_total             0.329849
passes_accuracy         -0.041644
passes_key               0.123260
tackles_total            0.114511
tackles_blocks           0.129577
tackles_interceptions    0.200601
duels_total              0.141126
duels_won                0.194143
dribbles_attempts        0.028403
dribbles_success         0.050103
dribbles_past                 NaN
fouls_drawn              0.097514
fouls_committed          0.058621
cards_yellow            -0.065287
cards_red               -0.036228
penalty_won              0.040795
penalty_commited        -0.033411
penalty_scored           0.047308
penalty_missed           0.020322
penalty_saved                 NaN
games_rating             1.000000
Name: games_rating, dtype: float64

In [39]:
MF_data.corr().loc[:,'games_rating']

shots_total              0.196254
shots_on                 0.202775
goals_total              0.108212
goals_conceded                NaN
goals_assists            0.225122
goals_saves                   NaN
passes_total             0.247190
passes_accuracy         -0.091593
passes_key               0.292662
tackles_total            0.072725
tackles_blocks           0.042291
tackles_interceptions    0.109713
duels_total              0.065305
duels_won                0.109789
dribbles_attempts        0.100019
dribbles_success         0.140089
dribbles_past                 NaN
fouls_drawn              0.138762
fouls_committed         -0.007034
cards_yellow            -0.048350
cards_red               -0.045791
penalty_won              0.015402
penalty_commited        -0.013168
penalty_scored           0.118298
penalty_missed           0.058984
penalty_saved                 NaN
games_rating             1.000000
Name: games_rating, dtype: float64

In [40]:
AT_data.corr().loc[:,'games_rating']

shots_total              0.226934
shots_on                 0.265326
goals_total              0.250575
goals_conceded                NaN
goals_assists            0.195385
goals_saves                   NaN
passes_total             0.261225
passes_accuracy         -0.066700
passes_key               0.229373
tackles_total           -0.005164
tackles_blocks           0.036858
tackles_interceptions    0.039001
duels_total              0.040414
duels_won                0.079726
dribbles_attempts        0.105839
dribbles_success         0.139723
dribbles_past                 NaN
fouls_drawn              0.118644
fouls_committed          0.006291
cards_yellow            -0.039022
cards_red               -0.033577
penalty_won              0.048095
penalty_commited         0.010363
penalty_scored           0.162789
penalty_missed           0.039414
penalty_saved                 NaN
games_rating             1.000000
Name: games_rating, dtype: float64

In [41]:
abs(AT_data.corr().loc[:,'games_rating'])>0.1

shots_total               True
shots_on                  True
goals_total               True
goals_conceded           False
goals_assists             True
goals_saves              False
passes_total              True
passes_accuracy          False
passes_key                True
tackles_total            False
tackles_blocks           False
tackles_interceptions    False
duels_total              False
duels_won                False
dribbles_attempts         True
dribbles_success          True
dribbles_past            False
fouls_drawn               True
fouls_committed          False
cards_yellow             False
cards_red                False
penalty_won              False
penalty_commited         False
penalty_scored            True
penalty_missed           False
penalty_saved            False
games_rating              True
Name: games_rating, dtype: bool

In [42]:
abs(MF_data.corr().loc[:,'games_rating'])>0.1

shots_total               True
shots_on                  True
goals_total               True
goals_conceded           False
goals_assists             True
goals_saves              False
passes_total              True
passes_accuracy          False
passes_key                True
tackles_total            False
tackles_blocks           False
tackles_interceptions     True
duels_total              False
duels_won                 True
dribbles_attempts         True
dribbles_success          True
dribbles_past            False
fouls_drawn               True
fouls_committed          False
cards_yellow             False
cards_red                False
penalty_won              False
penalty_commited         False
penalty_scored            True
penalty_missed           False
penalty_saved            False
games_rating              True
Name: games_rating, dtype: bool

In [43]:
abs(DF_data.corr().loc[:,'games_rating'])>0.1

shots_total               True
shots_on                  True
goals_total               True
goals_conceded           False
goals_assists             True
goals_saves              False
passes_total              True
passes_accuracy          False
passes_key                True
tackles_total             True
tackles_blocks            True
tackles_interceptions     True
duels_total               True
duels_won                 True
dribbles_attempts        False
dribbles_success         False
dribbles_past            False
fouls_drawn              False
fouls_committed          False
cards_yellow             False
cards_red                False
penalty_won              False
penalty_commited         False
penalty_scored           False
penalty_missed           False
penalty_saved            False
games_rating              True
Name: games_rating, dtype: bool

In [44]:
abs(GK_data.corr().loc[:,'games_rating'])>0.1

shots_total              False
shots_on                 False
goals_total              False
goals_conceded            True
goals_assists            False
goals_saves               True
passes_total             False
passes_accuracy          False
passes_key               False
tackles_total            False
tackles_blocks           False
tackles_interceptions    False
duels_total              False
duels_won                False
dribbles_attempts         True
dribbles_success          True
dribbles_past            False
fouls_drawn              False
fouls_committed           True
cards_yellow             False
cards_red                 True
penalty_won              False
penalty_commited         False
penalty_scored           False
penalty_missed           False
penalty_saved            False
games_rating              True
Name: games_rating, dtype: bool

In [45]:
GK_data[abs(GK_data.corr().loc[:,'games_rating'])>0.1]

C:\Users\rlagu\AppData\Local\Temp/ipykernel_22356/1711685966.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  GK_data[abs(GK_data.corr().loc[:,'games_rating'])>0.1]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).